services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      EUREKA_URI: "http://localhost:8761/eureka"
      REDIS_URL: "redis//localhost:6379"
    depends_on:
      - redis

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
